function escapeAttr(val) {
  return String(val).replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function renderComponentToHTML(comp) {
  const p = comp.props || {};
  switch (comp.type) {
    case 'button':
      return `<button class="pandora-btn pandora-btn--${p.size || 'md'}" style="background:${p.bgColor || '#0066cc'};color:${p.textColor || '#fff'};border-radius:${p.borderRadius || '6px'}">${escapeAttr(p.text || 'Click me')}</button>`;
    case 'card':
      return `<div class="pandora-card" style="background:${p.bgColor || '#fff'}">${p.image ? `<img src="${escapeAttr(p.image)}" alt="${escapeAttr(p.title || '')}" class="pandora-card__image"/>` : ''}<div class="pandora-card__body"><h3 class="pandora-card__title">${escapeAttr(p.title || 'Card Title')}</h3><p class="pandora-card__desc">${escapeAttr(p.description || 'Card description')}</p></div></div>`;
    case 'section':
      return `<section class="pandora-section" style="background:${p.bgColor || '#f5f5f5'};padding:${p.padding || '40px'};text-align:${p.textAlign || 'left'}">${p.title ? `<h2 class="pandora-section__title">${escapeAttr(p.title)}</h2>` : ''}<div class="pandora-section__content" style="min-height:100px"></div></section>`;
    case 'input':
      return `<div class="pandora-input-group">${p.label ? `<label class="pandora-input-group__label">${escapeAttr(p.label)}</label>` : ''}<input type="${escapeAttr(p.type || 'text')}" placeholder="${escapeAttr(p.placeholder || 'Enter text...')}" class="pandora-input" style="width:${p.width || '100%'}"/></div>`;
    case 'heading':
      return `<${p.level || 'h1'} class="pandora-heading pandora-heading--${p.level || 'h1'}" style="color:${p.color || '#333'};text-align:${p.textAlign || 'left'}">${escapeAttr(p.text || 'Your Heading')}</${p.level || 'h1'}>`;
    case 'text':
      return `<p class="pandora-text" style="color:${p.color || '#555'};font-size:${p.fontSize || '16px'};text-align:${p.textAlign || 'left'}">${escapeAttr(p.content || 'Your text content here...')}</p>`;
    case 'image':
      return `<img src="${escapeAttr(p.src || 'https://via.placeholder.com/400x300')}" alt="${escapeAttr(p.alt || 'Image')}" class="pandora-image" style="width:${p.width || '100%'};height:${p.height || 'auto'};border-radius:${p.borderRadius || '0px'}"/>`;
    case 'spacer':
      return `<div class="pandora-spacer" style="height:${p.height || '40px'}"></div>`;
    case 'divider':
      return `<hr class="pandora-divider" style="border-top:${p.thickness || '1px'} solid ${p.color || '#ddd'};margin:${p.margin || '20px 0'}"/>`;
    case 'video':
      return `<div class="pandora-video-wrapper" style="width:${p.width || '100%'};max-width:100%"><iframe src="${escapeAttr(p.src)}" height="${p.height || '315px'}" class="pandora-video" allowfullscreen title="video"></iframe></div>`;
    case 'list':
      const items = Array.isArray(p.items) ? p.items : ['Item 1', 'Item 2', 'Item 3'];
      const tag = p.style === 'number' ? 'ol' : 'ul';
      return `<${tag} class="pandora-list" style="color:${p.color || '#555'}">${items.map(i => `<li>${escapeAttr(i)}</li>`).join('')}</${tag}>`;
    case 'link':
      return `<a href="${escapeAttr(p.url || '#')}" target="${escapeAttr(p.target || '_blank')}" class="pandora-link" style="color:${p.color || '#0066cc'}">${escapeAttr(p.text || 'Click here')}</a>`;
    default:
      return `<div class="pandora-unknown" style="padding:10px;border:1px dashed #ddd">${comp.type}</div>`;
  }
}

function generateCSS(project) {
  return `/* ========================================
   Generated by Pandora Web Builder
   Project: ${project.title || 'Website'}
   ======================================== */

/* Reset & Base
  ======================================== */
*, *::before, *::after {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
  -webkit-text-size-adjust: 100%;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  line-height: 1.6;
  background: #fff;
  color: #333;
}

img {
  max-width: 100%;
  height: auto;
  display: block;
}

a {
  text-decoration: none;
}

/* Container
  ======================================== */
.pandora-container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
}

.pandora-container--fluid {
  max-width: 100%;
  padding: 0;
}

/* Button
  ======================================== */
.pandora-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: none;
  cursor: pointer;
  font-weight: 600;
  text-decoration: none;
  transition: all 0.2s ease;
  user-select: none;
}

.pandora-btn:hover {
  opacity: 0.9;
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(0,0,0,0.15);
}

.pandora-btn:active {
  transform: translateY(0);
}

.pandora-btn--sm {
  padding: 6px 14px;
  font-size: 13px;
}

.pandora-btn--md {
  padding: 10px 22px;
  font-size: 14px;
}

.pandora-btn--lg {
  padding: 14px 32px;
  font-size: 16px;
}

/* Card
  ======================================== */
.pandora-card {
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08);
  transition: box-shadow 0.2s ease;
}

.pandora-card:hover {
  box-shadow: 0 4px 16px rgba(0,0,0,0.12);
}

.pandora-card__image {
  width: 100%;
  height: 200px;
  object-fit: cover;
}

.pandora-card__body {
  padding: 20px;
}

.pandora-card__title {
  font-size: 18px;
  font-weight: 700;
  color: #111827;
  margin-bottom: 8px;
}

.pandora-card__desc {
  font-size: 14px;
  color: #6b7280;
  line-height: 1.6;
}

/* Section
  ======================================== */
.pandora-section {
  border-radius: 0;
}

.pandora-section__title {
  font-size: 24px;
  font-weight: 700;
  color: #111827;
  margin-bottom: 16px;
}

/* Input
  ======================================== */
.pandora-input-group {
  margin-bottom: 0;
}

.pandora-input-group__label {
  display: block;
  font-size: 14px;
  font-weight: 600;
  color: #374151;
  margin-bottom: 6px;
}

.pandora-input {
  padding: 10px 14px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 14px;
  color: #111827;
  background: #fff;
  transition: border-color 0.2s ease, box-shadow 0.2s ease;
  outline: none;
}

.pandora-input:focus {
  border-color: #0066cc;
  box-shadow: 0 0 0 3px rgba(0,102,204,0.15);
}

.pandora-input::placeholder {
  color: #9ca3af;
}

/* Heading
  ======================================== */
.pandora-heading {
  font-weight: 800;
  line-height: 1.2;
  margin: 0;
}

.pandora-heading--h1 { font-size: 2.5rem; }
.pandora-heading--h2 { font-size: 2rem; }
.pandora-heading--h3 { font-size: 1.75rem; }
.pandora-heading--h4 { font-size: 1.5rem; }
.pandora-heading--h5 { font-size: 1.25rem; }
.pandora-heading--h6 { font-size: 1rem; }

/* Text
  ======================================== */
.pandora-text {
  line-height: 1.7;
  margin: 0;
}

/* Image
  ======================================== */
.pandora-image {
  display: block;
  max-width: 100%;
}

/* Video
  ======================================== */
.pandora-video-wrapper {
  position: relative;
  overflow: hidden;
  border-radius: 8px;
}

.pandora-video {
  width: 100%;
  border: none;
}

/* List
  ======================================== */
.pandora-list {
  padding-left: 24px;
  line-height: 1.8;
}

.pandora-list li {
  font-size: 14px;
}

/* Link
  ======================================== */
.pandora-link {
  text-decoration: underline;
  font-weight: 500;
  transition: opacity 0.2s ease;
}

.pandora-link:hover {
  opacity: 0.8;
}

/* Divider
  ======================================== */
.pandora-divider {
  border: none;
}

/* Responsive
  ======================================== */
@media (max-width: 768px) {
  .pandora-heading--h1 { font-size: 1.8rem; }
  .pandora-heading--h2 { font-size: 1.5rem; }
  .pandora-heading--h3 { font-size: 1.3rem; }
  .pandora-container { padding: 0 16px; }
}

@media (max-width: 480px) {
  .pandora-btn--lg {
    width: 100%;
    padding: 12px 24px;
  }
}
`;
}

export function generateHTML(project) {
  const components = project.components || [];
  const css = generateCSS(project);
  const title = project.title || 'Website';
  const bodyContent = components.map(c =>
    `    <div class="pandora-component">${renderComponentToHTML(c)}</div>`
  ).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Built with Pandora Web Builder">
  <title>${escapeAttr(title)}</title>
  <style>
${css}
  </style>
</head>
<body>
  <div class="pandora-container">
${bodyContent}
  </div>
</body>
</html>`;
}

export function generateCSSOnly(project) {
  return generateCSS(project);
}

export function downloadHTML(project) {
  const html = generateHTML(project);
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.title || 'website'}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadCSS(project) {
  const css = generateCSSOnly(project);
  const blob = new Blob([css], { type: 'text/css;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.title || 'styles'}.css`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function previewHTML(project) {
  const html = generateHTML(project);
  const w = window.open('', '_blank', 'width=1200,height=800,scrollbars=yes');
  if (w) {
    w.document.write(html);
    w.document.close();
  }
}

export function getExportCode(project) {
  return {
    html: generateHTML(project),
    css: generateCSSOnly(project),
  };
}
